## input files generated by /home/unix/gavinha/software/code/git/scripts/titan/analysis/combineTITAN-ichor.R

library(data.table)
setDTthreads(threads = 2)
library(GenomicRanges)
library(stringr)
library(ggplot2)
library(reshape2)
source("util/plotting.R")

args <- commandArgs(TRUE)

options(stringsAsFactors=F, scipen=999, width=160)

ulpDir <- args[1] #path to titan's optimal solution
regionFile <- args[2] # ../../../metadata/AR_coord.txt (name chr start stop)
sampleListFile <- args[3] # ../../../metadata/sampleList_allCases.txt
outPrefix <- args[4] # CRPC10X42_WCDT_AR-enh_compare
outImage <- paste0(outPrefix,".RData")

colName <- "Corrected_Copy_Number"

cols <- c("No amplification"="grey", "Coamplification"="red", "Selective Enhancer"="#E69F00", "Selective AR"="#009E73")

logRbasedCN <- function(x, purity, ploidyT, cn = 2){
	ct <- (2^x * (cn * (1 - purity) + purity * ploidyT * (cn / 2)) - cn * (1 - purity)) / purity
	ct <- sapply(ct, max, 1/2^6)
	return(ct)
}

getCCF <- function(x, purity, ploidyT, ct1 = 3, ct2 = 4, cn = 2){
	a <- (2^x * (cn * (1 - purity) + purity * ploidyT * (cn / 2)) - cn * (1 - purity) - ct1 * purity)
	b <- purity * (ct2 - ct1)
	s <- a / b
	return(s)
}



ulpFiles <- list.files(ulpDir, pattern=".titan.ichor.cna.txt", full.names=T)
#ids <- gsub(".titan.ichor.cna.txt","", basename(ulpFiles))
ids <- str_extract(basename(ulpFiles), "[0-9A-Z-]+")
names(ulpFiles) <- ids
paramFiles <- list.files(ulpDir, pattern="params.txt", full.names=T)
ids <- str_extract(basename(paramFiles), "[0-9A-Za-z-]+")
names(paramFiles) <- ids
samples <- fread(sampleListFile, header=T)
ulpFiles <- ulpFiles[samples$Sample]; paramFiles <- paramFiles[samples$Sample]
numFiles <- length(ulpFiles)
regions <- fread(regionFile)
colnames(regions) <- c("Name", "Chr", "Start", "End")
regions.gr <- as(regions, "GRanges")
genomeStyle <- seqlevelsStyle(regions$Chr)
chrXstr <- "X"
seqlevelsStyle(chrXstr) <- genomeStyle

mat <- NULL
for (i in 1:numFiles){
	message("Analyzing ", ulpFiles[i])
	ulp <- fread(ulpFiles[i])
	params <- read.delim(paramFiles[i], header=F, as.is=T)
	purity <- 1 - as.numeric(params[1,2])
	ploidy <- as.numeric(params[2,2])
	ploidy.X <- ulp[Chr==chrXstr, median(get(colName), na.rm=T)]
	#ulp[chr!="X", logR_CN := logRbasedCN(copy, purity=purity, ploidy=ploidy, cn=2)]
	#ulp[chr=="X", logR_CN := logRbasedCN(copy, purity=purity, ploidy=ploidy, cn=1)]
	ulp <- ulp[!is.na(Chr) & !is.na(Start) & !is.na(End)]
	ulp.gr <- as(ulp, "GRanges")
	
	hits <- findOverlaps(query=ulp.gr, subject=regions.gr, type="any")
	ulp[queryHits(hits), region := regions[subjectHits(hits), Name]]
	ulp.region.mean <- na.omit(ulp[, lapply(.SD, mean), by=c("Sample","region"), .SDcols=c(colName,"LogRatio")])
	ulp.mean <- dcast(ulp.region.mean, Sample~region, value.var=colName)
	ulp.logR <- dcast(ulp.region.mean, Sample~region, value.var="LogRatio")
	mat <- rbind(mat, cbind(ulp.mean, logR = ulp.logR[,2:ncol(ulp.logR)], purity = purity, ploidy = ploidy, ploidy.X = ploidy.X))
}
save.image(outImage)

mat <- data.table(mat)
mat[is.finite(AR)]
colNames <- colnames(mat)[-1]

## apply correction to copy number in case the original values in the file are incorrect for some low purity samples
#mat[, AR := logRbasedCN(logR.AR, purity=purity, ploidy=ploidy, cn=1)]
#mat[, Enhancer := logRbasedCN(logR.Enhancer, purity=purity, ploidy=ploidy, cn=1)]

## get CN CCF
mat[, AR.CCF := getCCF(logR.AR, purity, ploidy, ct1=floor(AR), ct2=floor(AR)+1, cn=1)]
mat[, Enhancer.CCF := getCCF(logR.Enhancer, purity, ploidy, ct1=floor(Enhancer), ct2=floor(Enhancer)+1, cn=1)]
mat[is.infinite(AR.CCF) | AR.CCF > 1, AR.CCF := 1.0]
mat[AR.CCF < 0.1, AR.CCF := 0]
mat[is.infinite(Enhancer.CCF) | Enhancer.CCF > 1, Enhancer.CCF := 1.0]
mat[Enhancer.CCF < 0.1, Enhancer.CCF := 0]

mat[, AR.norm := AR / (ploidy / 2)]
mat[, Enhancer.norm :=  Enhancer / (ploidy / 2)]
#mat[, AR.norm := AR - (ploidy/2 - 1)]
#mat[, Enhancer.norm := Enhancer - (ploidy/2 - 1)]
#setnames(mat, c("AR", "Enhancer"), c("AR.abs", "Enhancer.abs"))

thres <- log2(1.5)
threshold <- 1.5
mat[, call := NULL]
mat[, FC := log2(Enhancer.norm / AR.norm)]
mat[AR.norm >= threshold & Enhancer.norm >= threshold, call := "Coamplification"]
mat[FC >= thres & AR.norm < threshold, call := "Selective Enhancer"]
mat[FC <= -1*thres & Enhancer.norm < threshold, call := "Selective AR"]
mat[is.na(call), call := "No amplification"]

mat$call <- factor(mat$call, levels = c("No amplification","Coamplification","Selective AR","Selective Enhancer"))
#lims <- c(min(mat[,2:3],na.rm=T), max(mat[,2:3], na.rm=T))
## plot purity vs enhancer minus AR (logRatio)
gp <- ggplot(mat, aes_string(x="AR.norm", y="Enhancer.norm", color="call", fill="call")) +
	geom_abline(slope=1, intercept=0, color="red") +
	geom_point(shape=21, size=4, alpha=0.75) +
	#geom_text_repel(aes(label=ID.label), color="black", size=3) +
	scale_fill_manual(values=cols) + #c("grey","red","#E69F00")) +
	scale_colour_manual(values=rep("black",length(mat[,unique(call)]))) +
	#scale_fill_manual(values=c("grey","grey")) +
	#scale_colour_manual(values=c("black", "black")) +
	scale_x_continuous(limits=c(0.5,280), breaks=c(1,2,8,32,128), labels=c(1,2,8,32,128), trans="log2") + 
	scale_y_continuous(limits=c(0.5,280), breaks=c(1,2,8,32,128), labels=c(1,2,8,32,128), trans="log2") +
	#annotation_logticks(base=2, scaled=TRUE, mid=unit(3, "mm")) +
	ylab(paste0(colNames[2]," CN")) + xlab(paste0(colNames[1]," CN")) +
	#ylim(c(0.5, 2.5)) + xlim(c(0.5,2.5)) +
 	theme_bw() + coord_fixed() +
	theme(axis.text.y=element_text(size=20), axis.text.x=element_text(size=16),
				axis.title=element_text(size=20), legend.key = element_blank(),
				plot.title=element_text(size=24, face="bold"), legend.position="none") 
outPlot <- paste0(outPrefix, "_AR-vs-Enh.pdf")
ggsave(gp, file=outPlot, width=4, height=4)

outFile <- paste0(outPrefix, "_AR-vs-Enh.txt")
fwrite(mat, file=outFile, col.names=T, row.names=F, quote=F, sep="\t")

outImage <- paste0(outPrefix,".RData")
save.image(outImage)

