
# this RData is generated by makeMatrixFromTITAN-ICHOR_segBased_hg38.R
load("CRPC10X_WCDT_geneMats.RData") #1=LOH and 0=notLOH

samples <- rownames(geneCNmat)

# cellular prevalance threshold
cp_threshold <- 0.8

#load ploidy information
ploidy <- read.csv("../../../metadata/all_ploidy.csv")[,c("sample","category","value")]

#table(as.character(ploidy$sample)==samples)

#load 159 gene list
gene_dat <- read.table("../../../metadata/combined_gene_list_159.txt", sep="\t", head=T)

gene_list <- as.character(gene_dat$symbol)
match_id <- as.vector(match(gene_list, colnames(geneCNmat)))
match_id <- match_id[!is.na(match_id)] 
names(match_id) <- gene_list


alteration_list <- list()

for(i in 1:length(match_id)){
	id <- match_id[i]
	gene <- names(id)
	print(gene)

	chr_gene <- as.character(gene_dat[gene_dat$symbol==gene,"chromosome"])

	cn <- geneCNmat[,id]
	loh <- geneLOHmat[,id]
	cp <- geneCFmat[,id]

	round_ploidy <- round(ploidy$value)

	# remove segments where cp < cp_threshold (0.8) however keep cp=NA (NEUT) and also Keep when cn >=4
	subclonal_id <- which(cp < cp_threshold & cn <4)
	
	if( length(subclonal_id)!=0 ){
		cn <- cn[-subclonal_id]
		loh <- loh[-subclonal_id]
		cp <- cp[-subclonal_id]
		round_ploidy <- round_ploidy[-subclonal_id]
	}

	# adjust 'Corrected_Copy_Number' based on ploidy information
	if( chr_gene != "chrX" ) {cn_adj <- cn/round_ploidy
	} else { 
		cn_adj <- cn/(round_ploidy/2)
	}

	cn_category <- rep(NA, length(samples))
	cn_category[which(cn_adj >= 2 & cn_adj <2.5)] <- "CN_Gain"
	cn_category[which(cn_adj >= 2.5)] <- "CN_Amplification"
	cn_category[which(cn_adj == 0)] <- "CN_Homozygous_Del"
	cn_category[which((cn_adj > 0 & cn_adj <1) & loh == 1)] <- "CN_Del_LOH"
	cn_category[which(cn_adj == 1 & loh == 1)] <- "Copy_Neutral_LOH"

	idx_avail <- which(!is.na(cn_category))

	#sample,category,value
	if( length(idx_avail)!=0 ) {
		alteration_list[[gene]] <- cbind(names(cn_adj)[idx_avail], gene, cn_category[idx_avail])
	} else {
		message("not available for gene ", gene)
		message(cn_adj," ", loh," ", cn_category)
	}
}

out_alteration_all <- do.call(rbind, alteration_list)
colnames(out_alteration_all) <- c("sample","category","value")
 
write.csv(out_alteration_all, sprintf("all_comut_CN_cp%s.csv", cp_threshold), quote=F)

